#tipos primitivos em Python
n = input('digite algo: ')
print('O tipo primitivo desse valor é ', type(n))
print('Só tem espaços? {}'.format(n.isspace()))
print('É um número? ', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiúsculas?', n.isupper())
print('Está em minúsculas?', n.islower())
print('Está capitalizado? ', n.istitle())
